Implement Comparable in GoGrid ErrorResponse
Gson collects errors in a TreeMap which requires a well-behaved
Comparable method.  This addresses a Java 7 GoGrid failure seen in
GridServerClientExpectTest.testGetServerCredentialsWhenNotFoundThrowsResourceNotFoundExceptionWithNiceMessage:

java.lang.ClassCastException: org.jclouds.gogrid.domain.internal.ErrorResponse cannot be cast to java.lang.Comparable